### PR TITLE
ibm-etag-headers bug fix

### LINKED ISSUE #616: ibm-etag-header crashes linter on incorrect specification
Hello,
I'm using the latest version of openapi-validator (IBM OpenAPI Validator (validator: 1.2.0; ruleset: 1.2.0)).

On invalid specification
```yml
openapi: 3.0.3

paths:
  /test:
    get:
      operationId: ruleBug
      parameters:
        - $ref: '#/components/schemas/NotAParameter'
      responses:
        '204':
          description: No content
components:
  schemas:
    NotAParameter:
      type: string
```

rule `ibm-etag-header` crashes whole linter:

```
[ERROR] There was a problem with spectral.
[ERROR] Error running Nimma
[ERROR] Additional error details:
[ERROR] AggregateError: Error running Nimma
    at Scope.destroy (/opt/linters/node_modules/nimma/dist/legacy/cjs/runtime/scope.js:137:13)
    at Nimma.eval (eval at query (/opt/linters/node_modules/nimma/dist/legacy/cjs/core/index.js:66:71), <anonymous>:182:11)
    at Nimma.query (/opt/linters/node_modules/nimma/dist/legacy/cjs/core/index.js:68:71)
    at execute (/opt/linters/node_modules/@stoplight/spectral-core/dist/runner/runner.js:82:11)
    at Runner.run (/opt/linters/node_modules/@stoplight/spectral-core/dist/runner/runner.js:51:13)
    at Spectral.runWithResolved (/opt/linters/node_modules/@stoplight/spectral-core/dist/spectral.js:55:22)
    at async Spectral.run (/opt/linters/node_modules/@stoplight/spectral-core/dist/spectral.js:63:17)
    at async runSpectral (/opt/linters/node_modules/ibm-openapi-validator/src/spectral/spectral-validator.js:39:27)
    at async runValidator (/opt/linters/node_modules/ibm-openapi-validator/src/cli-validator/run-validator.js:201:17) {
  [errors]: [
    RuntimeError: $.paths[*] threw: ErrorWithCause("Function \"\" threw an exception: Cannot read properties of undefined (reading 'toLowerCase')")
        at _callbacks.<computed> (/opt/linters/node_modules/nimma/dist/legacy/cjs/runtime/proxy-callbacks.js:34:21)
        at Scope.emit (/opt/linters/node_modules/nimma/dist/legacy/cjs/runtime/scope.js:109:19)
        ... 4 lines matching cause stack trace ...
        at _traverseBody (/opt/linters/node_modules/nimma/dist/legacy/cjs/runtime/traverse.js:17:5)
        at _traverse (/opt/linters/node_modules/nimma/dist/legacy/cjs/runtime/traverse.js:41:7)
        at Scope.traverse (/opt/linters/node_modules/nimma/dist/legacy/cjs/runtime/traverse.js:47:3)
        at Scope.traverse (/opt/linters/node_modules/nimma/dist/legacy/cjs/runtime/scope.js:94:25) {
      cause: [ErrorWithCause]
    }
  ]
}
```

Side issue – I wonder if it would be possible to output better error message containing rule name and perhaps rule input? I have bunch of rules specific to my projects, and it can be time-consuming to figure out which rule has error.

### PR DESCRIPTION
**Pull request by dpopp07**
## PR summary

The rule function did not account for missing required properties in parameter
objects and as a result, would crash when they were encountered. This commit
adds handling for this edge case, so that the rule will not crash.

Additionally, errors coming from the `nimma` package in Spectral bury the relevant info
and have been notoriously unhelpful for users and developers alike. This
commit updates the logic to parse out the helpful information and display
it in the error logs.

Resolves #616

### CODE REVIEW

File: packages/validator/src/cli-validator/run-validator.js [hunk 1]
```diff
@@ -254,4 +252,37 @@ function logError(description, message = '') {
...
+          try {
+            // Look for the filepath/line number at the top of the stack.
+            errInfo.topOfStack = cause.stack.split(' at ')[1];
+            errInfo.reason = cause.message;
+          } catch (e) {
+            logger.debug('Could not parse Spectral error information');
+            logger.debug(e.message);
+            logError(err);
+          } finally {
+            logger.error(`Cause: ${errInfo.reason}`);
```
Comment (padamstx) [inline packages/validator/src/cli-validator/run-validator.js:277]: Do we want the logError() call from the catch() AND the two logger.error() statements to be executed in the event of an exception while parsing error info?
Just checking...

**Review by padamstx — APPROVED** [review]
LGTM, just had one question to consider

File: packages/validator/src/cli-validator/run-validator.js (hunk 1 above)
Comment (dpopp07) [reply packages/validator/src/cli-validator/run-validator.js:277]: Good catch! I wasn't thinking. I didn't mean to use `finally`, I meant to make those error logs conditional on NOT throwing an exception. I'll make that update before merging

Comment (padamstx) [reply packages/validator/src/cli-validator/run-validator.js:277]: yeah, I think just putting them inside the try block and removing the finally block would do the trick.
