### PR TITLE
Security definition referencing

### LINKED ISSUE #39: securityScheme import:  Cannot read property 'toLowerCase' of undefined
##### VERSION
ibm-openapi-validator: 0.5.0

##### SUMMARY
Validator fails with ` Cannot read property 'toLowerCase' of undefined`  on securityScheme import like:
```
components:
  securitySchemes:
    securitySchemaN1:
      $ref: 'base.yaml#/components/securitySchemes/securitySchemaN1'
```

##### STACK TRACE
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at each (C:\example\node_modules\ibm-openapi-validator\src\plugins\validation\2and3\semantic-validators\security-definitions-ibm.js:31:21)
    at C:\example\node_modules\lodash\_createBaseFor.js:17:11
    at baseForOwn (C:\example\node_modules\lodash\_baseForOwn.js:13:20)
    at C:\example\node_modules\lodash\_createBaseEach.js:17:14
    at forEach (C:\example\node_modules\lodash\forEach.js:38:10)
    at Object.module.exports.validate (C:\example\node_modules\ibm-openapi-validator\src\plugins\validation\2and3\semantic-validators\security-definitions-ibm.js:23:3)
    at Object.keys.forEach.key (C:\example\node_modules\ibm-openapi-validator\src\cli-validator\utils\validator.js:70:40)
    at Array.forEach (<anonymous>)
    at validateSwagger (C:\example\node_modules\ibm-openapi-validator\src\cli-validator\utils\validator.js:69:30)
    at processInput (C:\example\node_modules\ibm-openapi-validator\src\cli-validator\runValidator.js:211:17)
```

##### STEPS TO REPRODUCE
1. Create `base.yaml`
```
components:
  securitySchemes:
    securitySchemaN1:
      description: example description
      type: apiKey
      in: cookie
      name: userAuthCookie
```

2. Create `main.yaml`
```
openapi: 3.0.0

paths: {}

components:

  securitySchemes:
    securitySchemaN1:
      $ref: 'base.yaml#/components/securitySchemes/securitySchemaN1'
```

3. Launch validator
```
$ lint-openapi main.yaml
[Warning] No .validaterc file found. The validator will run in default mode.
To configure the validator, create a .validaterc file.

[Error] There was a problem with a validator.
Cannot read property 'toLowerCase' of undefined
```

##### Expected result
ibm-openapi-validator will use the securityScheme definition inside main.yml without `Error`.

#### References

Per [openapi 3.0 specification schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml) the `securitySchemes` items can be a reference:

```
      securitySchemes:
        type: object
        patternProperties:
          '^[a-zA-Z0-9\.\-_]+$':
            oneOf:
              - $ref: '#/definitions/Reference'
              - $ref: '#/definitions/SecurityScheme'
```

### PR DESCRIPTION
**Pull request by SamerJaser96**
replaced instances of jsSpec with resolvedSpec in security-definitions-ibm so that resolved paths can be accessed when referenced, also added a test.

fixes #39

### CODE REVIEW

File: test/plugins/validation/2and3/security-definitions-ibm.js [hunk 1]
```diff
@@ -115,13 +116,40 @@ describe('validation plugin - semantic - security-definitions-ibm', function() {
...
 
-      const res = validate({ jsSpec: spec }, config);
+      const res = validate({ resolvedSpec: spec }, config);
       expect(res.errors.length).toEqual(0);
       expect(res.warnings.length).toEqual(0);
     });
   });
 
   describe('OpenAPI 3', function() {
+    it('should warn about an unused security definition', async function() {
```
Comment (dpopp07) [inline test/plugins/validation/2and3/security-definitions-ibm.js]: This name is also used by the test below it - we should not have duplicated test messages. Will you change this to `should follow references to security schemes` ?

File: test/plugins/validation/2and3/security-definitions-ibm.js [hunk 2]
```diff
@@ -12,7 +13,7 @@ const config = {
 
 describe('validation plugin - semantic - security-definitions-ibm', function() {
   describe('Swagger 2', function() {
-    it('should warn about an unused security definition', function() {
+    it('should follow references to security schemes', function() {
```
Comment (dpopp07) [inline test/plugins/validation/2and3/security-definitions-ibm.js]: This was not the test case to change - will you switch this back and update the test you added? See my comment below
